# This is a basic workflow to help you get started with Actions
name: internet.bj-frontend ci
'on':
  push:
    branches:
      - master
jobs:
  test: 
    runs-on: ubuntu-latest
    outputs:
      customtag: ${{steps.tager.outputs.tag}}
    steps:
    - uses: actions/checkout@v2
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql version: 12
        postgresql db: massdb
        postgresql user: mass
        postgresql password: password 
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
    - name: Install 
      run:
        pip install -r ./codes/requirements.txt
        pip install -r ./codes/requirements
    - name: Run Tests
      run: 
        python ./codes/manage.py test
        python ./codes/manage.py migrate 
    - name: Run Dockerfile
      uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose up -d
      
    
  
